services:
  keycloak:
    image: keycloak/keycloak:24.0.4
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev 
      - --import-realm
      - --override=false
    volumes:
      - ./kc/import:/opt/keycloak/data/import/:ro
      - ./kc/export:/opt/keycloak/data/export/:rw
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./.mongo-data/:/etc/mongo